#!/usr/bin/python
# -*- coding: utf-8 -*-

import sqlite3 as lite
import sys
import cPickle as pickle
scans = pickle.load(open("joeupdate.p","rb"))

db = lite.connect('test.db')

with db:
    
    cur = db.cursor()    
    
    cur.executemany("INSERT INTO Scans(SCAN, PROCTYPE, OBJECT, INTEG, BW, OBSEL, POLN, RESTFRQ, OBSTYPE, PROPID, DECJ2000, FILENAME, SESSION, MODE, VELDEF, VELOCITY, FILESIZE, POLN_NUM, NCHAN, OBSERVER, PROJID, BAND, VERSION, SESSION_MSGLEVEL, OBSAZ, MSGFLAG, SCANLEN, BADDATA, PROCNAME, RAJ2000, FILEDBID, FILEDATE, ObsParameterID, RECEIVER, OBSID, SESSION_MSGFLAG, SCANDBID, BACKEND) VALUES(:SCAN, :PROCTYPE, :OBJECT, :INTEG, :BW, :OBSEL, :POLN, :RESTFRQ, :OBSTYPE, :PROPID, :DECJ2000, :FILENAME, :SESSION, :MODE, :VELDEF, :VELOCITY, :FILESIZE, :POLN_NUM, :NCHAN, :OBSERVER, :PROJID, :BAND, :VERSION, :SESSION_MSGLEVEL, :OBSAZ, :MSGFLAG, :SCANLEN, :BADDATA, :PROCNAME, :RAJ2000, :FILEDBID, :FILEDATE, :ObsParameterID, :RECEIVER, :OBSID, :SESSION_MSGFLAG, :SCANDBID, :BACKEND)", scans)
