#!/usr/bin/python
# -*- coding: utf-8 -*-

import sqlite3 as lite
import sys
import cPickle as pickle
scans = pickle.load(open("scanList800_1000.p","rb"))

db = lite.connect('test.db')

with db:
    
    cur = db.cursor()    
    
    cur.execute("DROP TABLE IF EXISTS Scans")
    cur.execute('''CREATE TABLE Scans(
    SCAN INT,
    PROCTYPE TEXT,
    OBJECT TEXT,
    INTEG REAL,
    BW REAL,
    OBSEL REAL,
    POLN TEXT,
    RESTFRQ REAL,
    OBSTYPE TEXT,
    PROPID TEXT,
    DECJ2000 REAL,
    FILENAME TEXT,
    SESSION TEXT,
    MODE TEXT,
    VELDEF TEXT,
    VELOCITY REAL,
    FILESIZE INT,
    POLN_NUM TEXT,
    NCHAN TEXT,
    OBSERVER TEXT,
    PROJID TEXT,
    BAND TEXT,
    VERSION TEXT,
    SESSION_MSGLEVEL TEXT,
    OBSAZ REAL,
    MSGFLAG TEXT,
    SCANLEN INT,
    BADDATA TEXT,
    PROCNAME TEXT,
    RAJ2000 REAL,
    FILEDBID INT,
    FILEDATE DATETIME,
    ObsParameterID INT,
    RECEIVER TEXT,
    OBSID TEXT,
    SESSION_MSGFLAG TEXT,
    SCANDBID INT,
    BACKEND TEXT)
    '''
    )

    cur.executemany("INSERT INTO Scans(SCAN, PROCTYPE, OBJECT, INTEG, BW, OBSEL, POLN, RESTFRQ, OBSTYPE, PROPID, DECJ2000, FILENAME, SESSION, MODE, VELDEF, VELOCITY, FILESIZE, POLN_NUM, NCHAN, OBSERVER, PROJID, BAND, VERSION, SESSION_MSGLEVEL, OBSAZ, MSGFLAG, SCANLEN, BADDATA, PROCNAME, RAJ2000, FILEDBID, FILEDATE, ObsParameterID, RECEIVER, OBSID, SESSION_MSGFLAG, SCANDBID, BACKEND) VALUES(:SCAN, :PROCTYPE, :OBJECT, :INTEG, :BW, :OBSEL, :POLN, :RESTFRQ, :OBSTYPE, :PROPID, :DECJ2000, :FILENAME, :SESSION, :MODE, :VELDEF, :VELOCITY, :FILESIZE, :POLN_NUM, :NCHAN, :OBSERVER, :PROJID, :BAND, :VERSION, :SESSION_MSGLEVEL, :OBSAZ, :MSGFLAG, :SCANLEN, :BADDATA, :PROCNAME, :RAJ2000, :FILEDBID, :FILEDATE, :ObsParameterID, :RECEIVER, :OBSID, :SESSION_MSGFLAG, :SCANDBID, :BACKEND)", scans)
